## Тема “Вычисления с помощью Numpy”

#### Задание 1
Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.


In [31]:
import numpy as np

In [32]:
a = np.array([
    [1,2,3,3,1],
    [6,8,11,10,7]
])
a = a.transpose()
b = a.transpose()
mean_a = np.array([b[0].mean(), b[1].mean()])
mean_a

array([2. , 8.4])

#### Задание 2
Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.


In [33]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

#### Задание 3 (Ковариация 2х признаков)
Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.


In [34]:
a_centered_sp = a_centered[:,0] @ a_centered[:,1]
a_centered_sp/(len(a_centered) - 1)

2.0

#### Задание 4**
В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.



In [35]:
covar = np.cov(a.transpose())
covar

array([[1. , 2. ],
       [2. , 4.3]])

## Тема “Работа с данными в Pandas”


### Задание 1
Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].
Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные:  
[1, 1, 1, 2, 2, 3, 3],
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
[450, 300, 350, 500, 450, 370, 290].


In [36]:
import pandas as pd
import numpy as np

In [37]:
pd.DataFrame?

In [38]:
author_id = np.array([1,2,3])
author_id.size

3

In [39]:
author_id = [1,2,3]
author_name = ['Тургенев', 'Чехов', 'Островский']

authors = pd.DataFrame(np.array([author_id,author_name]).T,
                      columns=['author_id', 'author_name'])
authors

author_id author_name
0         1    Тургенев
1         2       Чехов
2         3  Островский

In [40]:
author_id = [1, 1, 1, 2, 2, 3, 3]
book_title = ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники']
price = [450, 300, 350, 500, 450, 370, 290]
np.array([author_id,author_id, price]).T

array([[  1,   1, 450],
       [  1,   1, 300],
       [  1,   1, 350],
       [  2,   2, 500],
       [  2,   2, 450],
       [  3,   3, 370],
       [  3,   3, 290]])

In [41]:
books = pd.DataFrame(np.array([author_id,book_title, price]).T, 
                   columns = ['author_id', 'book_title', 'price'])
books

author_id            book_title price
0         1           Отцы и дети   450
1         1                 Рудин   300
2         1     Дворянское гнездо   350
3         2      Толстый и тонкий   500
4         2       Дама с собачкой   450
5         3                 Гроза   370
6         3  Таланты и поклонники   290

### Задание 2
Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id


In [42]:
 pd.merge?

In [46]:
authors_price = authors.merge(books, how = 'right', on = 'author_id')
authors_price

author_id author_name            book_title price
0         1    Тургенев           Отцы и дети   450
1         1    Тургенев                 Рудин   300
2         1    Тургенев     Дворянское гнездо   350
3         2       Чехов      Толстый и тонкий   500
4         2       Чехов       Дама с собачкой   450
5         3  Островский                 Гроза   370
6         3  Островский  Таланты и поклонники   290

### Задание 3
Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.


In [64]:
authors_price.sort_values(by = 'price', inplace = True)
top5 = authors_price.tail(5)
top5
authors_price['price'] = pd.to_numeric(authors_price['price'] )

### Задание 4
Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца:
author_name, min_price, max_price и mean_price,
в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя цена на книги этого автора.


In [103]:
groupby = authors_price.groupby('author_name')

authors_stat = pd.DataFrame(np.array([author_name,groupby['price'].mean(), groupby['price'].min() ,groupby['price'].max() ]).T, columns = ['author_name', 'mean', 'min', 'max'])

In [104]:
authors_stat

author_name               mean  min  max
0    Тургенев              330.0  290  370
1       Чехов  366.6666666666667  300  450
2  Островский              475.0  450  500

pandas.core.series.Series